services:
  linter:
    build:
      context: ${HOST_PROJECT_PATH:-.}/..
      dockerfile: lint/Dockerfile
    image: pytest-repeated-lint:latest
    working_dir: /workspace
    volumes:
      - ${HOST_PROJECT_PATH:-..}:/workspace
    command: ./lint/lint_and_format.sh

