version: '3.8'
services:
  linter:
    build:
      context: ..
      dockerfile: lint/Dockerfile
    image: pytest-repeated-lint:latest
    command: ./lint/lint_and_format.sh
    working_dir: /app
    volumes:
      - ..:/app

